### ISSUE TITLE
Fail to build it

### ISSUE THREAD

**Issue by huming0618** [cazala/decentraland-shoal-scene#1]
### Platform
Windows 10
### Steps
0. `npm install -g decentraland`
1. download the source
2. `cd server`
3. `npm install`
4. `npm run build`

### Expect
The build should be successful 

### Actual Result
The error occurred with the content 
``metaverse-compiler' is not internal command or progam`

**Comment by cazala** [comment]
Hi @huming0618, could you confirm that you have this file inside the `server`'s local `node_modules` after running `npm install`?

```path-to-server/node_modules/.bin/metaverse-compiler```

if so, could you change the line `6` of the `package.json` inside the `server` directory from this:

```"build": "metaverse-compiler build.json",```

to this:

```"build": "./node_modules/.bin/metaverse-compiler build.json",```

finally try to run `npm run build` again and let me know if that worked :)

**Comment by cazala** [comment]
Also could you share the version of the CLI you have installed? run `npm list -g decentraland`

**Comment by huming0618** [comment]
HI, @cazala 
I checked the `.bin` folder under "server",, the ` metaverse-compiler` didn't exist,
here is the list of files:
- traceur
- traceur.cmd
- tsc
- tsc.cmd
- tsserver
- tsserver.cmd

I have tried the installation via "npm i"  again, but the result was same.

I checked the version for `dcl`, here is the version:
`decentraland@1.0.2`

**Comment by belohlavek** [comment]
Please try using the latest RC and `dcl preview`

**Comment by cazala** [comment]
This has been fixed on version 1.1.0 https://github.com/decentraland/cli/releases/tag/1.1.0
